NewsManagementSystem_Assigment01/Controllers/LoginController.cs
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Templates.BlazorIdentity.Pages.Manage;
using NewsManagementSystem_Assigment01.Models;
using System.Security.Claims;
using NewsManagementSystem_Assigment01.ViewModel;
using Microsoft.Extensions.Logging;
using Microsoft.AspNetCore.Authorization;
using System.Security.Principal;
using NewsManagementSystem_Assigment01.Services;

namespace NewsManagementSystem_Assigment01.Controllers
{
    public class LoginController : Controller
    {
        private readonly IConfiguration _config;
        private readonly ILogger<LoginController> _logger;
        private readonly AccountService _service;

        public LoginController(IConfiguration config, ILogger<LoginController> logger, AccountService service)
        {
            _config = config;
            _logger = logger;
            _service = service;
        }

        public IActionResult Index()
        {
            return View("SignIn");
        }

        [HttpPost]
        public async Task<IActionResult> SignInAsync(LoginViewModel model)
        {
            if (!ModelState.IsValid)
            {
                _logger.LogError("ModelState is invalid");
                return View(model);
            }

            var adminConfig = _config.GetSection("AdminAccount");
            string adminEmail = adminConfig["Email"];
            string adminPassword = adminConfig["Password"];

            if (model.Email == adminEmail && model.Password == adminPassword)
            {
                //Tạo ra list Claims(Các thông tin người dùng đang đăng nhập vào hệ thống) -> xác thực người dùng này là ai, có vai trò gì...
                var claims = new List<Claim>
                {
                    new Claim(ClaimTypes.Name, "Admin"),
                    new Claim(ClaimTypes.Email, model.Email),
                    new Claim(ClaimTypes.Role, "Admin")
                };

                //Lưu trữ list Claims trong CookieAuthentication
                var identity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

                //Thực hiện đăng nhập dựa trên Claims
                await HttpContext.SignInAsync(
                    CookieAuthenticationDefaults.AuthenticationScheme,
                    new ClaimsPrincipal(identity));

                return RedirectToAction("Index", "Home");
            }

            var user = _service.CheckLogin(model);
            if (user != null && user.IsActive)
            {
                var claims = new List<Claim>
                {
                    new Claim(ClaimTypes.Name, user.AccountName),
                    new Claim(ClaimTypes.Email, user.AccountEmail),
                    new Claim(ClaimTypes.Role, user.AccountRole.ToString()),
                    new Claim(ClaimTypes.NameIdentifier, user.AccountId.ToString())
                };
                //XÁC THỰC NGƯỜI DÙNG
                var identity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
                await HttpContext.SignInAsync(
                    CookieAuthenticationDefaults.AuthenticationScheme,
                    new ClaimsPrincipal(identity));

                return RedirectToAction("Index", "Home");
            }
            else
            {
                _logger.LogWarning("Đăng nhập thất bại: Sai email hoặc mật khẩu.");
                ModelState.AddModelError(string.Empty, "Email hoặc mật khẩu không đúng!");
                return View(model);
            }
        }

        [HttpGet]
        public async Task<IActionResult> RegisterAsync()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> RegisterAsync(RegisterViewModel model)
        {
            if (ModelState.IsValid)
            {
                var newAccount = new SystemAccount
                {
                    AccountId = model.AccountId,
                    AccountName = model.AccountName,
                    AccountEmail = model.AccountEmail,
                    AccountRole = model.AccountRole,
                    AccountPassword = model.AccountPassword,
                    IsActive = true
                };
                 
                _service.Register(newAccount);
                TempData["SuccessMessage"] = "Đắng ký thành công!";
                return RedirectToAction("Register");



            }
            return View();
        }


        [Authorize]
        public IActionResult SecurePage()
        {
            ViewBag.Name = HttpContext.User.Identity.Name;
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> LogOutAsync()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Profile()
        {
            var userIdString = User.FindFirstValue(ClaimTypes.NameIdentifier);
            if (string.IsNullOrEmpty(userIdString))
            {
                return NotFound("Không tìm thấy tài khoản");
            }

            if (!short.TryParse(userIdString, out short userId))
            {
                return BadRequest("ID người dùng không hợp lệ.");
            }

            var staff = _service.GetAccountById(userId);
            if (staff == null)
            {
                return NotFound("Không tìm thấy thông tin nhân viên.");
            }

            return View(staff);
        }





    }
}

NewsManagementSystem_Assigment01/Controllers/NewsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using NewsManagementSystem_Assigment01.Models;
using NewsManagementSystem_Assigment01.Services;
using NewsManagementSystem_Assigment01.ViewModel;
using System.Security.Claims;

namespace NewsManagementSystem_Assigment01.Controllers
{
    public class NewsController : Controller
    {
        private readonly NewsService _service;
        private readonly CategoryService _categoryService;
        private readonly ILogger<NewsController> _logger;
        private readonly SendMailService _sendMailService;

        public NewsController(NewsService service, CategoryService categoryService, ILogger<NewsController> logger, SendMailService sendMailService)
        {
            _service = service;
            _categoryService = categoryService;
            _logger = logger;
            _sendMailService = sendMailService;
        }

        public IActionResult Index()
        {

            return View();
        }

        [HttpGet]
        public IActionResult Create()
        {
            var model = new NewsArticleViewModel
            {
                CreatedDate = DateTime.Now, // Gán giá trị ngày giờ hiện tại
                CreatedById = User.FindFirstValue(ClaimTypes.NameIdentifier),//Lấy Id của user  
                UpdatedById = User.FindFirstValue(ClaimTypes.NameIdentifier),
                ModifiedDate = DateTime.Now,

            };
            var categories = _categoryService.GetCategories();
            // Tạo SelectList và gán vào ViewBag
            ViewBag.CategoryId = new SelectList(categories, "CategoryId", "CategoryName");

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(NewsArticleViewModel model)
        {
            if (ModelState.IsValid)
            {
                var newsArticle = new NewsArticle
                {
                    NewsArticleId = model.NewsArticleId,
                    NewsTitle = model.NewsTitle,
                    Headline = model.Headline,
                    NewsContent = model.NewsContent,
                    NewsSource = model.NewsSource,
                    CategoryId = model.CategoryId,
                    NewsStatus = model.NewsStatus,
                    CreatedDate = DateTime.Now,
                    CreatedById = short.TryParse(User.FindFirstValue(ClaimTypes.NameIdentifier), out short createdById) ? createdById : (short?)null,
                    UpdatedById = short.TryParse(User.FindFirstValue(ClaimTypes.NameIdentifier), out short updatedById) ? updatedById : (short?)null,
                    ModifiedDate = DateTime.Now
                };
                var mailContent = new MailContent();
                mailContent.To = "vietnq021103@gmail.com";
                mailContent.Subject = newsArticle.NewsTitle;
                mailContent.Body = "Được tạo bởi: " + User.FindFirstValue(ClaimTypes.Name) +
                    "<br>Chi tiết tin tức: <a href='https://localhost:7260/News/Details/" + newsArticle.NewsArticleId + "'>Xem chi tiết</a>";


                _sendMailService.SendMailAsync(mailContent);

                _service.Create(newsArticle);

                

                return RedirectToAction("Index", "Home"); // Điều hướng về danh sách bài viết
            }

            // Nếu có lỗi, load lại danh mục
            ViewBag.CategoryId = new SelectList(_categoryService.GetCategories(), "CategoryId", "CategoryName");
            return View(model);
        }

        [HttpGet]
        public IActionResult Delete(string id)
        {
            var newsArticle = _service.FindById(id);
            if (newsArticle == null)
            {
                return NotFound();
            }
            return View(newsArticle);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(string id)
        {
            var newsArticle = _service.FindById(id);
            if (newsArticle != null)
            {
                _service.Delete(newsArticle);
            }
            return RedirectToAction(nameof(Index), "Home");
        }


        [HttpGet]
        public IActionResult Edit(string id)
        {
            var newsArticle = _service.FindById(id);
            if (newsArticle == null)
            {
                return NotFound();
            }

            var categories = _categoryService.GetCategories();
            ViewBag.CategoryId = new SelectList(categories, "CategoryId", "CategoryName", newsArticle.CategoryId);

            var viewModel = new NewsArticleViewModel
            {
                NewsArticleId = newsArticle.NewsArticleId,
                NewsTitle = newsArticle.NewsTitle,
                Headline = newsArticle.Headline,
                NewsContent = newsArticle.NewsContent,
                NewsStatus = newsArticle.NewsStatus,
                CreatedDate = newsArticle.CreatedDate,
                NewsSource = newsArticle.NewsSource,
                CreatedById = newsArticle.CreatedById.ToString(),
                UpdatedById = newsArticle.UpdatedById.ToString(),
                ModifiedDate = newsArticle.ModifiedDate
            };

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(NewsArticleViewModel model)
        {
            if(ModelState.IsValid)
            {
                var newsArticle = _service.FindById(model.NewsArticleId);
                if (newsArticle == null)
                {
                    return NotFound();
                }
                else
                {
                    newsArticle.NewsTitle = model.NewsTitle;
                    newsArticle.Headline = model.Headline;
                    newsArticle.NewsContent = model.NewsContent;
                    newsArticle.NewsSource = model.NewsSource;
                    newsArticle.CategoryId = model.CategoryId;
                    newsArticle.NewsStatus = model.NewsStatus;
                    newsArticle.UpdatedById = short.TryParse(model.UpdatedById ?? User.FindFirstValue(ClaimTypes.NameIdentifier), out short result)
                         ? result
                        : (short?)null;
                    newsArticle.ModifiedDate = model.ModifiedDate;

                    _service.Update(newsArticle);
                    TempData["SuccessMessage"] = "Cập nhật bài viết thành công!";

                    return RedirectToAction("Edit", new { id = model.NewsArticleId });
                }

            }
            // Nếu có lỗi, load lại danh mục
            var categories = _categoryService.GetCategories();
            ViewBag.CategoryId = new SelectList(categories, "CategoryId", "CategoryName", model.CategoryId);
            return View(model);
        }


        public IActionResult Details(string id)
        {
            var newsArticle = _service.FindById(id);
            return View(newsArticle);
        }

        [HttpGet]
        public IActionResult History() 
        {
                var userIdString = User.FindFirstValue(ClaimTypes.NameIdentifier);
                if (string.IsNullOrEmpty(userIdString))
                {
                    return NotFound("Không tìm thấy tài khoản.");
                }

                short userId = short.Parse(userIdString);
                var newsList = _service.GetNewsByAccountID(userId);

                return View(newsList);
        }

    }
}

NewsManagementSystem_Assigment01/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@* @inject SignInManager<SystemAccount> signIn
@inject UserManager<SystemAccount> manager *@
@using System.Security.Claims

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FUNews</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/NewsManagementSystem_Assigment01.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FUNews</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Trang chủ</a>
                        </li>

                        @if (User.FindFirstValue(ClaimTypes.Role) == "1")
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Login" asp-action="Profile">Thông tin cá nhân</a>
                            </li>
                        }

                        @if (User.FindFirstValue(ClaimTypes.Role) == "1")
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="News" asp-action="Create">Tạo bài viết tin tức</a>
                            </li>
                        }
                        @if (User.FindFirstValue(ClaimTypes.Role) == "1")
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="News" asp-action="History">Lịch sử tạo tin tức</a>
                            </li>
                        }
                        @if (User.FindFirstValue(ClaimTypes.Role) == "Admin")
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Admin" asp-action="ManageUser">Quản lý người dùng</a>
                            </li>
                        }
                        @if (User.FindFirstValue(ClaimTypes.Role) == "Admin")
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Login" asp-action="Register">Đăng ký người dùng mới</a>
                            </li>
                        }
                        @if (User.FindFirstValue(ClaimTypes.Role) == "Admin")
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Admin" asp-action="ReportStatistics">Thống kê</a>
                            </li>
                        }
                        
                    </ul>
                </div>
                <ul class="navbar-nav">
                    @if (Context.User.Identity.Name != null)
                    {
                        <li class="nav-item">
                            <span class="nav-link">Xin chào, @Context.User.Identity.Name!</span>
                        </li>
                        <li class="nav-item">
                            <form class="form-inline" asp-controller="Login" asp-action="LogOut" method="post">
                                <button type="submit" class="nav-link btn btn-link text-dark">Đăng xuất</button>
                            </form>
                        </li>
                    }
                    else
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Login" asp-action="Index">Đăng Nhập</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Register">Đăng Ký</a>
                        </li>
                    }
                </ul>

            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
             @RenderBody() 
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - FUNews - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>